services:
  - type: web
    name: anonim-email
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/config
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false